import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
// app/layout.js or app/page.js
import Script from 'next/script';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <Script src='https://cdnjs.cloudflare.com/ajax/libs/three.js/r121/three.min.js'></Script>
      {/* <Script src='https://cdn.jsdelivr.net/npm/vanta@latest/dist/vanta.halo.min.js'></Script> */}
      <body className={inter.className}>{children}</body>
    </html>
  );
}
